joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

steer_bot_hardware_gazebo:
    rear_wheel  : 'rear_wheel_shaft_joint'
    front_steer : 'front_steer_shaft_joint'
    virtual_rear_wheels  : ['wheel_rr_joint', 'wheel_rl_joint']
    virtual_front_wheels : ['wheel_fr_joint', 'wheel_fl_joint']
    virtual_front_steers : ['wheel_fr_steer_joint', 'wheel_fl_steer_joint']

    # ackermann link mechanism
    enable_ackermann_link: true
    wheel_separation_w : 0.5
    wheel_separation_h : 0.79

gains:
  wheel_rr_joint  :  {p: 100000.0, d: 10.0, i: 0.50, i_clamp: 3.0}
  wheel_rl_joint   :  {p: 100000.0, d: 10.0, i: 0.50, i_clamp: 3.0}    

steer_drive_controller:
  type                          : "steer_drive_controller/SteerDriveController"
  rear_wheel                    : 'rear_wheel_shaft_joint'
  front_steer                   : 'front_steer_shaft_joint'
  #publish_rate                  : 100

  pose_covariance_diagonal      : [0.00001, 0.00001, 1000000000000.0, 1000000000000.0, 1000000000000.0, 0.001]
  twist_covariance_diagonal     : [0.01, 0.01, 0.01, 0.01, 0.01, 1.00]
  wheel_separation_h_multiplier : 1.0 #4 #15 # calibration parameter for angle odometory
  wheel_radius_multiplier       : 1.0 # calibration parameter for linear odometory
  steer_pos_multiplier          : 1.0 #3 # 1.5
  cmd_vel_timeout               : 4
  base_frame_id                 : base_link

  enable_odom_tf                : false
  wheel_separation_h            : 0.19 # retriieved from urdf joints
  wheel_radius                  : 0.028 # retrieved from urdf joint
